### PR TITLE
Merged with 5.0

### PR DESCRIPTION
**Pull request by lipis**

### CODE REVIEW

**Comment by lipis** [comment]
When I'm just running the following, everything works normally..
```
pybabel extract -F main/translations/babel.cfg --sort-by-file --omit-header -o main/translations/messages.pot main
```

But when I do `./run.py -u` I'm getting:

```
./run.py -u
.
.
.
extracting messages from main/model/user.py
extracting messages from main/templates/base.html (extensions="jinja2.ext.autoescape,jinja2.ext.with_")
Traceback (most recent call last):
  File "/Users/lipis/work/lipis/gae-init/git/babel/temp/venv/bin/pybabel", line 9, in <module>
    load_entry_point('Babel===2.0.dev0-20160628', 'console_scripts', 'pybabel')()
  File "/Users/lipis/work/lipis/gae-init/git/babel/temp/venv/lib/python2.7/site-packages/babel/messages/frontend.py", line 1151, in main
    return CommandLineInterface().run(sys.argv)
  File "/Users/lipis/work/lipis/gae-init/git/babel/temp/venv/lib/python2.7/site-packages/babel/messages/frontend.py", line 665, in run
    return getattr(self, cmdname)(args[1:])
  File "/Users/lipis/work/lipis/gae-init/git/babel/temp/venv/lib/python2.7/site-packages/babel/messages/frontend.py", line 919, in extract
    for filename, lineno, message, comments, context in extracted:
  File "/Users/lipis/work/lipis/gae-init/git/babel/temp/venv/lib/python2.7/site-packages/babel/messages/extract.py", line 163, in extract_from_dir
    strip_comment_tags):
  File "/Users/lipis/work/lipis/gae-init/git/babel/temp/venv/lib/python2.7/site-packages/babel/messages/extract.py", line 190, in extract_from_file
    strip_comment_tags))
  File "/Users/lipis/work/lipis/gae-init/git/babel/temp/venv/lib/python2.7/site-packages/babel/messages/extract.py", line 249, in extract
    func = entry_point.load(require=True)
  File "/Users/lipis/work/lipis/gae-init/git/babel/temp/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2228, in load
    self.require(*args, **kwargs)
  File "/Users/lipis/work/lipis/gae-init/git/babel/temp/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2245, in require
    items = working_set.resolve(reqs, env, installer)
  File "/Users/lipis/work/lipis/gae-init/git/babel/temp/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (Babel 2.0.dev0-20160628 (/Users/lipis/work/lipis/gae-init/git/babel/temp/venv/lib/python2.7/site-packages), Requirement.parse('Babel>=0.8'))
pybabel extract -k _ -k __ -F main/translations/babel.cfg --sort-by-file --omit-header -o main/translations/messages.pot main
extracting messages from main/__init__.py
.
.
.
```

Any idea @gmist?

**Comment by gmist** [comment]
possible here
```
pkg_resources.VersionConflict: (Babel 2.0.dev0-20160628 (/Users/lipis/work/lipis/gae-init/git/babel/temp/venv/lib/python2.7/site-packages), Requirement.parse('Babel>=0.8'))
```

**Comment by lipis** [comment]
of course `pybabel` that I have in the system is older I guess :/ https://github.com/python-babel/babel/pull/84

**Comment by gmist** [comment]
Try to replace ```git+https://github.com/joernhees/babel@zipcompat-build``` by ```babel==2.3.4```

**Comment by lipis** [comment]
I'm getting white page.. :/ It's all kind of fucked up :( Plus that wouldn't work as we need to be able to zip it.. I tried to do something with it (https://github.com/lipis/babel/pull/1) but failed misserable.. if you have any idea or our Dr. @joernhees would be awesome to resolve it..

**Comment by joernhees** [comment]
no Dr. yet ;(

could you retry with `git+https://github.com/joernhees/babel@zipcompat_2.3.4-build`?

**Comment by lipis** [comment]
It was looking promising as it managed generate the files and correctly but when I run the app locally I get a white screen as result.. blank..

**Comment by gmist** [comment]
I have no idea, sorry

**Comment by gmist** [comment]
it took more than 2 hours... but I found blank page error - @lipis please check ```base.html``` :))))

**Comment by joernhees** [comment]
so this wasn't even my fault? :D 💃

**Comment by lipis** [comment]
We opened sourced Wire today https://github.com/wireapp/wire and I'm away now without a computer.. thanks a bunch and I will check my stupidity on sunday :)

**Comment by lipis** [comment]
https://m.reddit.com/u/Lipis/activity?sort=hot&activity=submitted wrong weekend to be without a proper internet and computer :)

**Comment by lipis** [comment]
@gmist LOL.. :) thanks for finding out my stupidity...!!
@joernhees It looks like it works..!! I'll make further tests with deployments to verify it.. once on more stable internet! Thanks a lot..

**Comment by lipis** [comment]
@joernhees So it seems that it worked all the way :) :godmode: 🍻 

shall we maybe rename the brunch to something like `zip-2.3.4` to keep it shorter?

**Comment by joernhees** [comment]
brunch? sure! ;) copied the branch...

still working on a test for it, so it finally can go into babel upstream

**Comment by lipis** [comment]
@joernhees brunch 🍔 🍅 🍛 🍰 🍹 :) That would be even better! Thanks..

**Pull request merged**
